[colors.bright]
black = "0x90817b"
blue = "0x81d0c9"
cyan = "0xf08d71"
green = "0xa6cd77"
magenta = "0x9fa0e1"
red = "0xf86882"
white = "0xe4e3e1"
yellow = "0xf0c66f"

[colors.normal]
black = "0x1f1e1c"
blue = "0x81d0c9"
cyan = "0xf08d71"
green = "0xa6cd77"
magenta = "0x9fa0e1"
red = "0xf86882"
white = "0xe4e3e1"
yellow = "0xf0c66f"

[colors.primary]
background = "0x312c2b"
foreground = "0xe4e3e1"
